### ISSUE TITLE
Testing Script on 20.10

### ISSUE THREAD

**Issue by TechnologyMan101** [TechnologyMan101/pop-os-setup-script#2]
Testers will need to do a fresh install of 20.04 LTS, run the script in full install mode, change theme to Pop-Light, change background to something other than the default, then upgrade to 20.10. After upgrading, report here if packages stayed installed, if the background or theme changed, and which sources are installed. If the sources were removed, run the script in full mode again and report the results. Also check if the main Pop!_OS source code PPA and Proprietary source code repo are still installed. If not, add `http://ppa.launchpad.net/system76/pop/ubuntu` with repoman and enable it, then add `http://apt.pop-os.org/proprietary` and keep it disabled.

Testing the script in minimal install mode is unnecessary because all of the packages are from the system repos and all of the packages are also included in full install mode.

**Comment by TechnologyMan101** [comment]
This will be done 1 week after Pop!_OS 20.10 is released.

**Comment by harrisonmoss** [comment]
**HELLO** _yay_

**Comment by harrisonmoss** [comment]
**AND YOU CAN FIGURE OUT WHY.**

**Comment by harrisonmoss** [comment]
Ok, i'll try it

**Comment by harrisonmoss** [comment]
ODD

**Comment by TechnologyMan101** [comment]
Confirmed working with 20.10. This was verified with Ubuntu 20.10 Beta. Pop!_OS is near identical in repositories to Ubuntu so there should not be a problem.
